// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeBank.Models;

namespace RecipeBank.Migrations
{
    [DbContext(typeof(RecipeBankContext))]
    partial class RecipeBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("RecipeBank.Models.RecipeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("image_url");

                    b.Property<string>("publisher");

                    b.Property<string>("steps");

                    b.Property<string>("tag");

                    b.Property<string>("title");

                    b.HasKey("Id");

                    b.ToTable("RecipeItem");
                });
#pragma warning restore 612, 618
        }
    }
}
